# Generated by Django 6.1.1 on 2026-09-21 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст новини')),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='Дата публікації')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закріпити нагорі')),
                ('order', models.IntegerField(default=100, verbose_name='Порядок (менше число = вище)')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-is_pinned', 'order', '-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='По батькові')),
                ('position', models.CharField(max_length=100, verbose_name='Посада (напр., Доцент)')),
                ('degree', models.CharField(blank=True, max_length=100, verbose_name='Науковий ступінь')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                ('order', models.IntegerField(default=100, verbose_name='Порядок сортування (менше число = вище)')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
                'ordering': ['order', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Фото')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='department.news')),
            ],
            options={
                'verbose_name': 'Фотографію',
                'verbose_name_plural': 'Галерея новини',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва дисципліни')),
                ('description', models.TextField(verbose_name='Опис')),
                ('study_year', models.PositiveSmallIntegerField(verbose_name='Курс (рік навчання)')),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Семестр')),
                ('teachers', models.ManyToManyField(related_name='courses', to='department.teacher', verbose_name='Викладачі')),
            ],
            options={
                'verbose_name': 'Дисципліна',
                'verbose_name_plural': 'Дисципліни',
            },
        ),
    ]
