# Generated by Django 6.1.1 on 2026-09-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(choices=[('c1', '1 Курс'), ('c2', '2 Курс'), ('c3', '3 Курс'), ('c4', '4 Курс'), ('m1', 'Магістратура'), ('m2', 'Магістратура 2')], max_length=5, verbose_name='Курс')),
                ('day', models.CharField(choices=[('Понеділок', 'Понеділок'), ('Вівторок', 'Вівторок'), ('Середа', 'Середа'), ('Четвер', 'Четвер'), ("П'ятниця", "П'ятниця"), ('Субота', 'Субота')], max_length=20, verbose_name='День тижня')),
                ('timeStart', models.CharField(help_text='Формат HH:MM (наприклад, 08:40)', max_length=10, verbose_name='Час початку')),
                ('timeEnd', models.CharField(help_text='Формат HH:MM (наприклад, 10:15)', max_length=10, verbose_name='Час закінчення')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('type', models.CharField(max_length=50, verbose_name='Тип (Лекція, Практика, Лаб)')),
                ('external_teacher', models.CharField(blank=True, help_text='Заповніть, якщо викладача немає в списку нашої кафедри', max_length=150, null=True, verbose_name='Викладач (інша кафедра)')),
                ('room', models.CharField(max_length=100, verbose_name='Аудиторія (або Google Meet)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання на онлайн пару')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.teacher', verbose_name='Викладач (наша кафедра)')),
            ],
            options={
                'verbose_name': 'Пара (Розклад)',
                'verbose_name_plural': 'Розклад занять',
                'ordering': ['course_id', 'day', 'timeStart'],
            },
        ),
    ]
