# Generated by Django 6.1.1 on 2026-09-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('week_1', 'Тимчасовий (1 Тиждень)'), ('week_2', 'Тимчасовий (2 Тиждень)'), ('permanent', 'Постійний розклад')], default='permanent', max_length=20, verbose_name='Статус розкладу'),
        ),
    ]
