# Generated by Django 6.1.1 on 2026-09-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_schedule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(choices=[('c1', '1 Курс'), ('c2', '2 Курс'), ('c3', '3 Курс'), ('c4', '4 Курс'), ('m1', 'Магістратура'), ('m2', 'Магістратура 2')], max_length=5, verbose_name='Курс')),
                ('status', models.CharField(choices=[('week_1', 'Тимчасовий (1 Тиждень)'), ('week_2', 'Тимчасовий (2 Тиждень)'), ('permanent', 'Постійний розклад')], max_length=20, verbose_name='Статус розкладу')),
                ('google_sheet_url', models.URLField(help_text='Вставте сюди посилання на розклад', verbose_name='Посилання на Google Таблицю (/pubhtml)')),
                ('sync_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата синхронізації')),
                ('result_message', models.TextField(blank=True, null=True, verbose_name='Результат виконання')),
            ],
            options={
                'verbose_name': 'Синхронізація розкладу',
                'verbose_name_plural': 'Синхронізації (Google Sheets)',
            },
        ),
    ]
