# Generated by Django 6.1.1 on 2026-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_schedulesync'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='subgroup',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Підгрупа'),
        ),
    ]
