# Generated by Django 6.1.1 on 2026-09-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_schedule_subgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва конференції')),
                ('content', models.TextField(verbose_name='Текст / Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='conferences/', verbose_name='Фото')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання на матеріали/реєстрацію')),
                ('date_held', models.DateField(blank=True, null=True, verbose_name='Дата проведення')),
            ],
            options={
                'verbose_name': 'Конференція',
                'verbose_name_plural': 'Конференції',
                'ordering': ['-date_held'],
            },
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва олімпіади')),
                ('content', models.TextField(verbose_name='Текст / Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='olympiads/', verbose_name='Фото')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання на реєстрацію/результати')),
                ('date_held', models.DateField(blank=True, null=True, verbose_name='Дата проведення')),
            ],
            options={
                'verbose_name': 'Олімпіада',
                'verbose_name_plural': 'Олімпіади',
                'ordering': ['-date_held'],
            },
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('c1', '1 Курс'), ('c2', '2 Курс'), ('c3', '3 Курс'), ('c4', '4 Курс'), ('m1', 'Магістратура'), ('m2', 'Магістратура 2')], max_length=5, verbose_name='Курс')),
                ('group_name', models.CharField(help_text='Залиште порожнім, якщо куратор на весь потік', max_length=50, verbose_name='Назва групи (напр., МІТ-11)')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curatorships', to='department.teacher', verbose_name='Викладач (Куратор)')),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Куратори груп',
                'ordering': ['course', 'group_name'],
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва посібника')),
                ('description', models.TextField(verbose_name='Анотація / Опис')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='textbooks/', verbose_name='Обкладинка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання на завантаження/перегляд')),
                ('external_authors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Інші автори (вручну)')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік видання')),
                ('teachers', models.ManyToManyField(blank=True, related_name='textbooks', to='department.teacher', verbose_name='Автори (з кафедри)')),
            ],
            options={
                'verbose_name': 'Навчальний посібник',
                'verbose_name_plural': 'Навчальні посібники',
                'ordering': ['-publication_year', 'title'],
            },
        ),
    ]
