# Generated by Django 6.1.1 on 2026-09-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_conference_olympiad_curator_textbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Назва групи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Група посилань',
                'verbose_name_plural': 'Групи посилань',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EduSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (якір)')),
                ('intro', models.TextField(blank=True, verbose_name='Вступний текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показувати в меню')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Розділ освітнього процесу',
                'verbose_name_plural': 'Освітній процес: розділи',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EduLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Текст посилання')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Дрібний підпис (роки тощо)')),
                ('url', models.URLField(blank=True, verbose_name='Посилання')),
                ('file', models.FileField(blank=True, upload_to='edu/', verbose_name='Або файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='department.edugroup')),
            ],
            options={
                'verbose_name': 'Посилання',
                'verbose_name_plural': 'Посилання',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EduImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='edu/images/')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='Підпис')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='department.edusection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='edugroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='department.edusection'),
        ),
    ]
