# Generated by Django 6.1.1 on 2026-09-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_edugroup_edusection_edulink_eduimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ПІБ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відправки')),
            ],
            options={
                'verbose_name': 'Пропозиція до програми',
                'verbose_name_plural': 'Пропозиції до програм',
                'ordering': ['-created_at'],
            },
        ),
    ]
