# Generated by Django 6.1.1 on 2026-09-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_programfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['degree', 'category', 'subcategory', 'title'], 'verbose_name': 'Дисципліна', 'verbose_name_plural': 'Дисципліни (Силабуси)'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='study_year',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('mandatory', "Обов'язкові компоненти"), ('block', 'Вибіркові блоки'), ('list', 'Вибір з переліку'), ('free', 'Факультативи / Вільний вибір')], default='mandatory', max_length=20, verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('bsc', 'Бакалавр'), ('msc', 'Магістр')], default='bsc', max_length=10, verbose_name='Рівень вищої освіти'),
        ),
        migrations.AddField(
            model_name='course',
            name='rpnd_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabi/', verbose_name='РПНД (Файл)'),
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, verbose_name="Підкатегорія (напр. '1 КУРС' або 'Блок 1')"),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabi/', verbose_name='Силабус / РП (Файл)'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Викладачі (ПІБ та регалії)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='department.teacher', verbose_name="Прив'язка до профілів викладачів"),
        ),
    ]
