# Generated by Django 6.1.1 on 2026-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_alter_course_options_remove_course_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Підпис до фото')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фотографія')),
                ('category', models.CharField(choices=[('science', 'Наукова діяльність'), ('education', 'Навчальний процес'), ('students', 'Студентське життя'), ('events', 'Івенти та Хакатони')], default='students', max_length=50, verbose_name='Категорія')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Фотографія',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-created_at'],
            },
        ),
    ]
